package br.com.cervicare.historico.domain.enums;

public enum MetodoContraceptivo {
    ANTICONCEPCIONAL_ORAL_PROGESTAGENIO_ISOLADO,
    ANTICONCEPCIONAL_ORAL_COMBINADO,
    IMPLANTE_ETONOGESTREL,
    DIU_HORMONAL,
    DIU_NAO_HORMONAL,
    LAQUEADURA_TUBARIA,
    ANEL_VAGINAL,
    ADESIVO_TRANSDERMICO,
    PRESERVATIVO,
    NENHUM
}