-- V5__Atualizacao_Enums_PCR.sql
-- Atualiza as colunas ENUM para os novos domínios clínicos e reestrutura o PCR para suportar múltiplos tipos de HPV

ALTER TABLE saude_sexual MODIFY COLUMN mac ENUM('ANTICONCEPCIONAL_ORAL_PROGESTAGENIO_ISOLADO', 'ANTICONCEPCIONAL_ORAL_COMBINADO', 'IMPLANTE_ETONOGESTREL', 'DIU_HORMONAL', 'DIU_NAO_HORMONAL', 'LAQUEADURA_TUBARIA', 'ANEL_VAGINAL', 'ADESIVO_TRANSDERMICO', 'PRESERVATIVO', 'NENHUM') NOT NULL;
ALTER TABLE procedimento MODIFY COLUMN resultado ENUM('NIC_1', 'NIC_2', 'NIC_3', 'ADENOCARCINOMA_IN_SITU', 'MICROINVASOR_IA1', 'MICROINVASOR_IA2', 'CARCINOMA_ESCAMOSO_INVASOR', 'ADENOCARCINOMA_INVASOR', 'OUTROS') NOT NULL;
ALTER TABLE colposcopia MODIFY COLUMN grau_lesao ENUM('ACHADO_MAIOR', 'ACHADO_MENOR', 'INVASAO') NULL;
ALTER TABLE citologia MODIFY COLUMN resultado ENUM('NILM', 'ASC_US', 'LSIL', 'ASC_H', 'HSIL', 'HSIL_COM_CARACTERISTICAS_SUGESTIVAS_DE_INVASAO', 'CARCINOMA_DE_CELULAS_ESCAMOSAS', 'AGC_SOE', 'AGC_ENDOCERVICAL', 'AGC_ENDOMETRIAL', 'AGC_FAVORECENDO_NEOPLASIA', 'AIS_ENDOCERVICAL', 'ADENOCARCINOMA_ENDOCERVICAL', 'ADENOCARCINOMA_ENDOMETRIAL', 'ADENOCARCINOMA_EXTRAUTERINO', 'ADENOCARCINOMA_SOE') NOT NULL;

-- Remove a coluna antiga de tipo único do PCR
ALTER TABLE pcr_dna_hpv DROP COLUMN tipo_hpv;

-- Cria a nova tabela para suportar N tipos de HPV por exame de PCR
CREATE TABLE IF NOT EXISTS pcr_dna_hpv_tipo (
  id_tipo INT AUTO_INCREMENT PRIMARY KEY,
  hpv_tipo ENUM('HPV_6', 'HPV_11', 'HPV_16', 'HPV_18', 'OUTROS') NOT NULL,
  id_pcr INT NOT NULL,
  CONSTRAINT fk_pcr_dna_hpv_tipo_pcr FOREIGN KEY (id_pcr) REFERENCES pcr_dna_hpv (id_exame) ON DELETE CASCADE
);