import { StyleSheet } from "react-native";

import { FontFamilies, Spacing, Theme, Typography } from "@/constants/theme";

export const styles = StyleSheet.create({
  safeArea: { flex: 1 },
  screen: { flex: 1 },
  content: { paddingBottom: 100 },
  header: {
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.two,
    gap: Spacing.three,
  },
  headerTop: { flexDirection: "row", justifyContent: "space-between" },
  progress: { flexDirection: "row", gap: Spacing.one },
  progressSegment: { flex: 1, height: 4, borderRadius: 4 },
  title: {
    fontFamily: FontFamilies.detail,
    fontSize: Typography.sizes.title,
    lineHeight: Typography.lineHeights.title,
  },
  section: { marginTop: Spacing.three },
  sectionTitle: {
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: Theme.border,
  },
  inputField: {
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.three,
    gap: Spacing.two,
    borderBottomWidth: 1,
    borderBottomColor: Theme.border,
  },
  textInput: {
    borderWidth: 1,
    borderColor: Theme.border,
    borderRadius: 12,
    minHeight: 48,
    paddingHorizontal: Spacing.two,
    fontFamily: FontFamilies.primary,
    fontSize: Typography.sizes.input,
    color: Theme.text,
  },
  dateRow: { flexDirection: "row", gap: Spacing.two },
  row: {
    minHeight: 60,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
    borderBottomWidth: 1,
    borderBottomColor: Theme.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  counter: { flexDirection: "row", alignItems: "center", gap: Spacing.two },
  counterValue: {
    fontFamily: FontFamilies.detail,
    fontSize: Typography.sizes.subtitle,
  },
  roundButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: Theme.border,
    alignItems: "center",
    justifyContent: "center",
  },
  roundButtonActive: {
    backgroundColor: Theme.primary,
    borderColor: Theme.primary,
  },
  choiceRow: {
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
    gap: Spacing.two,
    borderBottomWidth: 1,
    borderBottomColor: Theme.border,
  },
  choiceList: { flexDirection: "row", flexWrap: "wrap", gap: Spacing.one },
  choice: {
    borderWidth: 1,
    borderColor: Theme.border,
    borderRadius: 20,
    paddingHorizontal: Spacing.two,
    paddingVertical: Spacing.one,
  },
  choiceSelected: {
    backgroundColor: Theme.primary,
    borderColor: Theme.primary,
  },
  optionRow: {
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
    gap: Spacing.two,
    borderBottomWidth: 1,
    borderBottomColor: Theme.border,
  },
  summaryRow: {
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.three,
    flexDirection: "row",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: Theme.border,
  },
  review: { backgroundColor: Theme.background, marginTop: Spacing.three },
  reviewBlock: {
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
    gap: Spacing.one,
    borderBottomWidth: 1,
    borderBottomColor: Theme.border,
  },
  error: { paddingHorizontal: Spacing.three, paddingVertical: Spacing.two },
  continue: {
    position: "absolute",
    bottom: 16,
    left: Spacing.three,
    right: Spacing.three,
    minHeight: 54,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Theme.primary,
  },
  continueText: { fontWeight: Typography.weights.bold },
  pressed: { opacity: 0.8 },
});
