export * from './profissionais/profissionais'
export * from './perfil/perfil'
export * from './pacientes/pacientes'
export * from './novo-paciente/novo-paciente'
//export * from './paciente/paciente'
