package br.com.cervicare.atendimento.domain.enums;

public enum ResultadoCitologia {
    NILM, ASC_US, LSIL, ASC_H, HSIL, 
    HSIL_COM_CARACTERISTICAS_SUGESTIVAS_DE_INVASAO, 
    CARCINOMA_DE_CELULAS_ESCAMOSAS, AGC_SOE, AGC_ENDOCERVICAL, 
    AGC_ENDOMETRIAL, AGC_FAVORECENDO_NEOPLASIA, AIS_ENDOCERVICAL, 
    ADENOCARCINOMA_ENDOCERVICAL, ADENOCARCINOMA_ENDOMETRIAL, 
    ADENOCARCINOMA_EXTRAUTERINO, ADENOCARCINOMA_SOE
}